apiVersion: v1
kind: Service
metadata:
  name: payment
  labels:
    app: payment
    service: payment
spec:
  ports:
    - port: 8083
      name: http
  selector:
    app: payment

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: payment-details
  labels:
    account: payment

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-v1
  labels:
    app: payment
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
      version: v1
  template:
    metadata:
      labels:
        app: payment
        version: v1
    spec:
      serviceAccountName: payment-details
      containers:
        - name: payment
          image: istio-payment-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8083
