version: '3.8'


services:
  flight-api:
    build:
      context: ../flight-api
      dockerfile: Dockerfile
    # remove container_name so Compose can auto-name multiple instances
    # container_name: flight
    expose:
      - "9090"
    volumes:
      - ../flight-api/target:/app/target
    networks:
      - istio
    # if you deploy this as a Docker Swarm stack, this will give you 2 replicas:
    deploy:
      replicas: 2

  auth-api:
    build:
      context: ../auth-api
      dockerfile: Dockerfile
    # container_name: auth
    ports:
      - "8000:8000"
    volumes:
      - ../auth-api/target:/app/target
    networks:
      - istio

  frontend:
    build:
      context: ../airlines-app  # Assuming the frontend app is in the 'frontend' directory
      dockerfile: Dockerfile  # Use the Dockerfile you provided for the frontend
    container_name: airlines-app
    ports:
      - "4200:80"  # NGINX will serve the frontend on port 80
    networks:
      - istio
    depends_on:
      - flight-api  # Correct service name
      - auth-api    # Correct service name

networks:
  istio:
    driver: bridge
