#version: '3.8'
#
#services:
#  flight-api:
#    build:
#      context: ../flight-api
#      dockerfile: Dockerfile
#    expose:
#      - "9090"
#    volumes:
#      - ../flight-api/target:/app/target
#    networks:
#      - istio
#    deploy:
#      replicas: 2
#
#  auth-api:
#    build:
#      context: ../auth-api
#      dockerfile: Dockerfile
#    ports:
#      - "8000:8000"
#    volumes:
#      - ../auth-api/target:/app/target
#    networks:
#      - istio
#
#  frontend:
#    build:
#      context: ../airlines-app
#      dockerfile: Dockerfile
#    container_name: airlines-app
#    ports:
#      - "4200:80"
#    networks:
#      - istio
#    depends_on:
#      - flight-api
#      - auth-api
#
#  zookeeper:
#    image: confluentinc/cp-zookeeper:7.6.0
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    networks:
#      - istio
#
#  kafka:
#    image: confluentinc/cp-kafka:7.6.0
#    ports:
#      - "9092:9092"
#    depends_on:
#      - zookeeper
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#    networks:
#      - istio
#
#networks:
#  istio:
#    driver: bridge


services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1