apiVersion: v1
kind: Service
metadata:
  name: product
  labels:
    app: product
    service: product
spec:
  ports:
  - port: 9090
    name: http
  selector:
    app: product
    
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-details
  labels:
    account: product
    
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
  labels:
    app: product
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
      version: v1
  template:
    metadata:
      labels:
        app: product
        version: v1
    spec:
      serviceAccountName: product-details
      containers:
        - name: product
          image: product:latest # Local image name
          imagePullPolicy: Never # Ensures Kubernetes doesn't try to pull from a registry
          ports:
            - containerPort: 9090

---