apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: shared-routing
spec:
  hosts:
    - "*"
  gateways:
    - shared-gateway
  http:
    # Route for /login to auth service
    - match:
        - uri:
            prefix: /login
      route:
        - destination:
            host: auth
            port:
              number: 8000
    - match:
        - uri:
            exact: /auth/country
      route:
        - destination:
            host: auth
            port:
              number: 8000

    # Route for /auth/profile to auth service
    - match:
        - uri:
            prefix: /auth
      route:
        - destination:
            host: auth
            port:
              number: 8000

    # Route for /sign-up to airlines-app service
    - match:
        - uri:
            prefix: /sign-up
      route:
        - destination:
            host: airlines-app
            port:
              number: 80

    # Routes for other static resources to airlines-app service
    - match:
        - uri:
            prefix: /polyfills-FFHMD2TL.js
      route:
        - destination:
            host: airlines-app
            port:
              number: 80

    - match:
        - uri:
            prefix: /main-2UZL65YY.js
      route:
        - destination:
            host: airlines-app
            port:
              number: 80

    - match:
        - uri:
            prefix: /styles-CXCWI5IP.css
      route:
        - destination:
            host: airlines-app
            port:
              number: 80

    - match:
        - uri:
            prefix: /favicon.ico
      route:
        - destination:
            host: airlines-app
            port:
              number: 80

    - match:
        - uri:
            prefix: /home
      route:
        - destination:
            host: airlines-app
            port:
              number: 80

    # Route for /flight to flight service
    - match:
        - uri:
            prefix: /flight
      route:
        - destination:
            host: flight
            port:
              number: 9090

# Fault injection example (uncomment to use):
#    fault:
#      delay:
#        percentage:
#          value: 10 # 10% requests delayed
#        fixedDelay: 5s
#      abort:
#        percentage:
#          value: 10 # 10% requests aborted
#        httpStatus: 500
#    retries:
#      attempts: 3
#      perTryTimeout: 2s
#    timeout: 5s
