apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: shared-routing
spec:
  hosts:
    - "*"
  gateways:
    - shared-gateway
  http:
    - match:
        - uri:
            prefix: /order
      route:
        - destination:
            host: order
            port:
              number: 8000
      fault: # simulate failure
        delay:
          percentage:
            value: 10 # simulates delay in 10% of requests
          fixedDelay: 5s
        abort:
          percentage:
            value: 10 # simulates failure by aborting 10% of request and returning HTTP 500
          httpStatus: 500
      retries:
        attempts: 3
        perTryTimeout: 2s # if a request fails, Istio will retry the request up to 3 times, with each retry attemprt allowed
      timeout: 5s
---