apiVersion: v1
kind: Service
metadata:
  name: notification
  labels:
    app: notification
    service: notification
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: notification

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-details
  labels:
    account: notification

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-v1
  labels:
    app: notification
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
      version: v1
  template:
    metadata:
      labels:
        app: notification
        version: v1
    spec:
      serviceAccountName: notification-details
      containers:
        - name: notification
          image: istio-notification-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
